class Solution {
    public int poorPigs(int buckets, int minutesToDie, int minutesToTest) {
        int pigsCount = 0;
        int time = minutesToTest / minutesToDie + 1;
        while(Math.pow(time , pigsCount) < buckets){
            pigsCount++;
        }

        return pigsCount;

        /*Calculate the max time for a pig to test buckets...
        Note that, max time will not be (minutesToTest / minutesToDie)...
        Thinking about all pigs drinking all buckets at last, but no one died immediately, so the
        poison bucket is the last bucket...
        Initialize the required minimum number of pigs...
        To find the minimum number of pigs, find the minimum req_pigs such that Math.pow(max_time,
        req_pigs) >= buckets...
        Increment until it will be greater or equals to bucket...
        Return the required minimum number of pigs...
         */
    }
}